### PR TITLE
Stack Code Template Added

### PR DESCRIPTION
**Pull request by sayskar500**

### CODE REVIEW

**Comment by sayskar500** [comment]
well what if I want to contribute more files ? ... and why the need to delete ?

**Comment by HemangJoshi** [comment]
you can contribute more files but for the mentioned topics only 
@sayskar500

**Comment by HemangJoshi** [comment]
I am unable to understand your question regarding the deletion of files can you please rephrase it
@sayskar500

**Comment by sayskar500** [comment]
do u mean that for hacktoberfest only a single contribution will be counted?

**Comment by HemangJoshi** [comment]
you have to contribute at least 4 times
a contribution consists of making the pull request and getting it merged.
it will be counted after the 7-day verification period is over.
you can check your progress from this link
[https://hacktoberfest.com/profile/](url)
@sayskar500 
pls do follow the guidelines provided
and make meaning full contribution

**Comment by sayskar500** [comment]
I can contribute more than once to the same project, right?

Also, did you find my contribution not meaningful? (I just wanted to know)

**Pull request merged**
